<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="48" hostname="linux-ThinkPad-E460" name="cases.CheckBoxCase" tests="92" failures="6" timestamp="04 Aug 2018 17:43:10 GMT" time="22.183" errors="8">
  <testcase name="beforeMethod" time="0.000" classname="cases.CheckBoxCase">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at bricks.PapaBless.beforeMethod(PapaBless.java:393)
at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:520)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at GrandpaBless.main(GrandpaBless.java:81)
]]>
    </error>
  </testcase> <!-- beforeMethod -->
  <testcase name="beforeMethod" time="0.001" classname="cases.CheckBoxCase">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at bricks.PapaBless.beforeMethod(PapaBless.java:393)
at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:520)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at GrandpaBless.main(GrandpaBless.java:81)
]]>
    </error>
  </testcase> <!-- beforeMethod -->
  <testcase name="beforeMethod" time="0.000" classname="cases.CheckBoxCase">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at bricks.PapaBless.beforeMethod(PapaBless.java:393)
at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:520)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at GrandpaBless.main(GrandpaBless.java:81)
]]>
    </error>
  </testcase> <!-- beforeMethod -->
  <testcase name="beforeMethod" time="0.000" classname="cases.CheckBoxCase">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at bricks.PapaBless.beforeMethod(PapaBless.java:393)
at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:520)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at GrandpaBless.main(GrandpaBless.java:81)
]]>
    </error>
  </testcase> <!-- beforeMethod -->
  <testcase name="beforeMethod" time="0.001" classname="cases.CheckBoxCase">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at bricks.PapaBless.beforeMethod(PapaBless.java:393)
at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:520)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at GrandpaBless.main(GrandpaBless.java:81)
]]>
    </error>
  </testcase> <!-- beforeMethod -->
  <testcase name="beforeMethod" time="0.000" classname="cases.CheckBoxCase">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at bricks.PapaBless.beforeMethod(PapaBless.java:393)
at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:520)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at GrandpaBless.main(GrandpaBless.java:81)
]]>
    </error>
  </testcase> <!-- beforeMethod -->
  <testcase name="beforeMethod" time="0.000" classname="cases.CheckBoxCase">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at bricks.PapaBless.beforeMethod(PapaBless.java:393)
at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:520)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at GrandpaBless.main(GrandpaBless.java:81)
]]>
    </error>
  </testcase> <!-- beforeMethod -->
  <testcase name="beforeMethod" time="0.000" classname="cases.CheckBoxCase">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at bricks.PapaBless.beforeMethod(PapaBless.java:393)
at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:520)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at GrandpaBless.main(GrandpaBless.java:81)
]]>
    </error>
  </testcase> <!-- beforeMethod -->
  <testcase name="checkBoxOneTwo" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- checkBoxOneTwo -->
  <testcase name="checkBoxOneThree" time="0.656" classname="cases.CheckBoxCase"/>
  <testcase name="checkBoxOneThree" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- checkBoxOneThree -->
  <testcase name="checkBoxTwoThree" time="0.665" classname="cases.CheckBoxCase"/>
  <testcase name="checkBoxNone" time="0.207" classname="cases.CheckBoxCase"/>
  <testcase name="checkBoxTwoThree" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- checkBoxTwoThree -->
  <testcase name="checkBoxTwoThree" time="0.355" classname="cases.CheckBoxCase"/>
  <testcase name="intentionalFailcheckBox" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- intentionalFailcheckBox -->
  <testcase name="checkBoxOneThree" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- checkBoxOneThree -->
  <testcase name="checkBoxOneThree" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- checkBoxOneThree -->
  <testcase name="intentionalFailcheckBox" time="0.365" classname="cases.CheckBoxCase">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at cases.CheckBoxCase.intentionalFailcheckBox(CheckBoxCase.java:62)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at GrandpaBless.main(GrandpaBless.java:81)
]]>
    </failure>
  </testcase> <!-- intentionalFailcheckBox -->
  <testcase name="checkBoxNone" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- checkBoxNone -->
  <testcase name="checkBoxAll" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- checkBoxAll -->
  <testcase name="checkBoxNone" time="0.190" classname="cases.CheckBoxCase"/>
  <testcase name="checkBoxOneTwo" time="0.691" classname="cases.CheckBoxCase"/>
  <testcase name="checkBoxOneThree" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- checkBoxOneThree -->
  <testcase name="checkBoxOneThree" time="0.713" classname="cases.CheckBoxCase"/>
  <testcase name="checkBoxOneTwo" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- checkBoxOneTwo -->
  <testcase name="checkBoxOneTwo" time="0.353" classname="cases.CheckBoxCase"/>
  <testcase name="checkBoxAll" time="1.043" classname="cases.CheckBoxCase"/>
  <testcase name="checkBoxNone" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- checkBoxNone -->
  <testcase name="checkBoxOneThree" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- checkBoxOneThree -->
  <testcase name="checkBoxOneThree" time="0.673" classname="cases.CheckBoxCase"/>
  <testcase name="checkBoxTwoThree" time="0.657" classname="cases.CheckBoxCase"/>
  <testcase name="checkBoxNone" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- checkBoxNone -->
  <testcase name="checkBoxTwoThree" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- checkBoxTwoThree -->
  <testcase name="checkBoxOneThree" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- checkBoxOneThree -->
  <testcase name="checkBoxNone" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- checkBoxNone -->
  <testcase name="checkBoxTwoThree" time="0.328" classname="cases.CheckBoxCase"/>
  <testcase name="checkBoxOneTwo" time="0.665" classname="cases.CheckBoxCase"/>
  <testcase name="intentionalFailcheckBox" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- intentionalFailcheckBox -->
  <testcase name="checkBoxNone" time="0.806" classname="cases.CheckBoxCase"/>
  <testcase name="checkBoxAll" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- checkBoxAll -->
  <testcase name="checkBoxAll" time="2.947" classname="cases.CheckBoxCase"/>
  <testcase name="checkBoxNone" time="0.162" classname="cases.CheckBoxCase"/>
  <testcase name="checkBoxOneTwo" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- checkBoxOneTwo -->
  <testcase name="checkBoxOneThree" time="0.357" classname="cases.CheckBoxCase"/>
  <testcase name="checkBoxNone" time="0.202" classname="cases.CheckBoxCase"/>
  <testcase name="checkBoxNone" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- checkBoxNone -->
  <testcase name="checkBoxAll" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- checkBoxAll -->
  <testcase name="checkBoxTwoThree" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- checkBoxTwoThree -->
  <testcase name="intentionalFailcheckBox" time="0.649" classname="cases.CheckBoxCase">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at cases.CheckBoxCase.intentionalFailcheckBox(CheckBoxCase.java:62)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at GrandpaBless.main(GrandpaBless.java:81)
]]>
    </failure>
  </testcase> <!-- intentionalFailcheckBox -->
  <testcase name="checkBoxNone" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- checkBoxNone -->
  <testcase name="checkBoxNone" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- checkBoxNone -->
  <testcase name="checkBoxOneTwo" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- checkBoxOneTwo -->
  <testcase name="intentionalFailcheckBox" time="0.351" classname="cases.CheckBoxCase">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at cases.CheckBoxCase.intentionalFailcheckBox(CheckBoxCase.java:62)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at GrandpaBless.main(GrandpaBless.java:81)
]]>
    </failure>
  </testcase> <!-- intentionalFailcheckBox -->
  <testcase name="checkBoxOneThree" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- checkBoxOneThree -->
  <testcase name="intentionalFailcheckBox" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- intentionalFailcheckBox -->
  <testcase name="intentionalFailcheckBox" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- intentionalFailcheckBox -->
  <testcase name="checkBoxTwoThree" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- checkBoxTwoThree -->
  <testcase name="intentionalFailcheckBox" time="0.669" classname="cases.CheckBoxCase">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at cases.CheckBoxCase.intentionalFailcheckBox(CheckBoxCase.java:62)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at GrandpaBless.main(GrandpaBless.java:81)
]]>
    </failure>
  </testcase> <!-- intentionalFailcheckBox -->
  <testcase name="checkBoxTwoThree" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- checkBoxTwoThree -->
  <testcase name="checkBoxOneThree" time="0.335" classname="cases.CheckBoxCase"/>
  <testcase name="intentionalFailcheckBox" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- intentionalFailcheckBox -->
  <testcase name="checkBoxTwoThree" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- checkBoxTwoThree -->
  <testcase name="intentionalFailcheckBox" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- intentionalFailcheckBox -->
  <testcase name="checkBoxTwoThree" time="0.737" classname="cases.CheckBoxCase"/>
  <testcase name="intentionalFailcheckBox" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- intentionalFailcheckBox -->
  <testcase name="checkBoxOneThree" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- checkBoxOneThree -->
  <testcase name="intentionalFailcheckBox" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- intentionalFailcheckBox -->
  <testcase name="checkBoxAll" time="0.949" classname="cases.CheckBoxCase"/>
  <testcase name="checkBoxAll" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- checkBoxAll -->
  <testcase name="checkBoxAll" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- checkBoxAll -->
  <testcase name="checkBoxNone" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- checkBoxNone -->
  <testcase name="checkBoxTwoThree" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- checkBoxTwoThree -->
  <testcase name="checkBoxTwoThree" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- checkBoxTwoThree -->
  <testcase name="checkBoxOneTwo" time="0.705" classname="cases.CheckBoxCase"/>
  <testcase name="checkBoxAll" time="0.953" classname="cases.CheckBoxCase"/>
  <testcase name="checkBoxOneTwo" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- checkBoxOneTwo -->
  <testcase name="checkBoxOneTwo" time="0.664" classname="cases.CheckBoxCase"/>
  <testcase name="checkBoxAll" time="0.424" classname="cases.CheckBoxCase"/>
  <testcase name="checkBoxTwoThree" time="0.663" classname="cases.CheckBoxCase"/>
  <testcase name="checkBoxOneTwo" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- checkBoxOneTwo -->
  <testcase name="checkBoxOneTwo" time="0.334" classname="cases.CheckBoxCase"/>
  <testcase name="checkBoxOneTwo" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- checkBoxOneTwo -->
  <testcase name="checkBoxOneTwo" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- checkBoxOneTwo -->
  <testcase name="checkBoxNone" time="0.186" classname="cases.CheckBoxCase"/>
  <testcase name="checkBoxOneThree" time="0.672" classname="cases.CheckBoxCase"/>
  <testcase name="checkBoxAll" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- checkBoxAll -->
  <testcase name="checkBoxAll" time="0.522" classname="cases.CheckBoxCase"/>
  <testcase name="intentionalFailcheckBox" time="0.662" classname="cases.CheckBoxCase">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at cases.CheckBoxCase.intentionalFailcheckBox(CheckBoxCase.java:62)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at GrandpaBless.main(GrandpaBless.java:81)
]]>
    </failure>
  </testcase> <!-- intentionalFailcheckBox -->
  <testcase name="intentionalFailcheckBox" time="0.671" classname="cases.CheckBoxCase">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at cases.CheckBoxCase.intentionalFailcheckBox(CheckBoxCase.java:62)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at GrandpaBless.main(GrandpaBless.java:81)
]]>
    </failure>
  </testcase> <!-- intentionalFailcheckBox -->
  <testcase name="checkBoxAll" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- checkBoxAll -->
  <testcase name="checkBoxAll" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- checkBoxAll -->
</testsuite> <!-- cases.CheckBoxCase -->
