<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="18" hostname="linux-ThinkPad-E460" name="cases.CheckBoxCase" tests="57" failures="6" timestamp="29 Jul 2018 18:56:51 GMT" time="23.023" errors="3">
  <testcase name="beforeMethod" time="0.000" classname="cases.CheckBoxCase">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at bricks.PapaBless.beforeMethod(PapaBless.java:337)
at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:520)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at GrandpaBless.main(GrandpaBless.java:81)
]]>
    </error>
  </testcase> <!-- beforeMethod -->
  <testcase name="beforeClass" time="0.018" classname="cases.CheckBoxCase">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at bricks.PapaBless.beforeClass(PapaBless.java:329)
at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:168)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at GrandpaBless.main(GrandpaBless.java:81)
]]>
    </error>
  </testcase> <!-- beforeClass -->
  <testcase name="beforeMethod" time="0.000" classname="cases.CheckBoxCase">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at bricks.PapaBless.beforeMethod(PapaBless.java:337)
at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:520)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at GrandpaBless.main(GrandpaBless.java:81)
]]>
    </error>
  </testcase> <!-- beforeMethod -->
  <testcase name="intentionalFailcheckBox" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- intentionalFailcheckBox -->
  <testcase name="intentionalFailcheckBox" time="0.406" classname="cases.CheckBoxCase">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at cases.CheckBoxCase.intentionalFailcheckBox(CheckBoxCase.java:62)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at GrandpaBless.main(GrandpaBless.java:81)
]]>
    </failure>
  </testcase> <!-- intentionalFailcheckBox -->
  <testcase name="intentionalFailcheckBox" time="0.734" classname="cases.CheckBoxCase">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at cases.CheckBoxCase.intentionalFailcheckBox(CheckBoxCase.java:62)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at GrandpaBless.main(GrandpaBless.java:81)
]]>
    </failure>
  </testcase> <!-- intentionalFailcheckBox -->
  <testcase name="checkBoxNone" time="0.224" classname="cases.CheckBoxCase"/>
  <testcase name="checkBoxOneTwo" time="0.347" classname="cases.CheckBoxCase"/>
  <testcase name="checkBoxTwoThree" time="0.319" classname="cases.CheckBoxCase"/>
  <testcase name="checkBoxOneThree" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- checkBoxOneThree -->
  <testcase name="checkBoxTwoThree" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- checkBoxTwoThree -->
  <testcase name="checkBoxOneThree" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- checkBoxOneThree -->
  <testcase name="checkBoxOneThree" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- checkBoxOneThree -->
  <testcase name="checkBoxNone" time="0.204" classname="cases.CheckBoxCase"/>
  <testcase name="checkBoxOneTwo" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- checkBoxOneTwo -->
  <testcase name="checkBoxTwoThree" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- checkBoxTwoThree -->
  <testcase name="checkBoxNone" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- checkBoxNone -->
  <testcase name="intentionalFailcheckBox" time="0.760" classname="cases.CheckBoxCase">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at cases.CheckBoxCase.intentionalFailcheckBox(CheckBoxCase.java:62)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at GrandpaBless.main(GrandpaBless.java:81)
]]>
    </failure>
  </testcase> <!-- intentionalFailcheckBox -->
  <testcase name="checkBoxOneThree" time="0.763" classname="cases.CheckBoxCase"/>
  <testcase name="checkBoxNone" time="0.248" classname="cases.CheckBoxCase"/>
  <testcase name="checkBoxNone" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- checkBoxNone -->
  <testcase name="checkBoxNone" time="1.588" classname="cases.CheckBoxCase"/>
  <testcase name="checkBoxOneTwo" time="0.707" classname="cases.CheckBoxCase"/>
  <testcase name="checkBoxAll" time="1.108" classname="cases.CheckBoxCase"/>
  <testcase name="checkBoxOneThree" time="0.762" classname="cases.CheckBoxCase"/>
  <testcase name="checkBoxAll" time="1.065" classname="cases.CheckBoxCase"/>
  <testcase name="checkBoxNone" time="0.202" classname="cases.CheckBoxCase"/>
  <testcase name="checkBoxOneTwo" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- checkBoxOneTwo -->
  <testcase name="checkBoxTwoThree" time="0.342" classname="cases.CheckBoxCase"/>
  <testcase name="checkBoxAll" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- checkBoxAll -->
  <testcase name="checkBoxOneTwo" time="0.320" classname="cases.CheckBoxCase"/>
  <testcase name="checkBoxOneTwo" time="0.739" classname="cases.CheckBoxCase"/>
  <testcase name="checkBoxTwoThree" time="0.741" classname="cases.CheckBoxCase"/>
  <testcase name="checkBoxOneThree" time="0.751" classname="cases.CheckBoxCase"/>
  <testcase name="intentionalFailcheckBox" time="0.799" classname="cases.CheckBoxCase">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at cases.CheckBoxCase.intentionalFailcheckBox(CheckBoxCase.java:62)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at GrandpaBless.main(GrandpaBless.java:81)
]]>
    </failure>
  </testcase> <!-- intentionalFailcheckBox -->
  <testcase name="checkBoxOneTwo" time="0.764" classname="cases.CheckBoxCase"/>
  <testcase name="intentionalFailcheckBox" time="0.372" classname="cases.CheckBoxCase">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at cases.CheckBoxCase.intentionalFailcheckBox(CheckBoxCase.java:62)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at GrandpaBless.main(GrandpaBless.java:81)
]]>
    </failure>
  </testcase> <!-- intentionalFailcheckBox -->
  <testcase name="checkBoxAll" time="0.431" classname="cases.CheckBoxCase"/>
  <testcase name="intentionalFailcheckBox" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- intentionalFailcheckBox -->
  <testcase name="checkBoxTwoThree" time="0.711" classname="cases.CheckBoxCase"/>
  <testcase name="checkBoxOneTwo" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- checkBoxOneTwo -->
  <testcase name="checkBoxTwoThree" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- checkBoxTwoThree -->
  <testcase name="checkBoxAll" time="1.097" classname="cases.CheckBoxCase"/>
  <testcase name="checkBoxAll" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- checkBoxAll -->
  <testcase name="checkBoxNone" time="0.184" classname="cases.CheckBoxCase"/>
  <testcase name="intentionalFailcheckBox" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- intentionalFailcheckBox -->
  <testcase name="checkBoxAll" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- checkBoxAll -->
  <testcase name="checkBoxAll" time="0.413" classname="cases.CheckBoxCase"/>
  <testcase name="checkBoxOneThree" time="0.811" classname="cases.CheckBoxCase"/>
  <testcase name="checkBoxOneThree" time="0.324" classname="cases.CheckBoxCase"/>
  <testcase name="intentionalFailcheckBox" time="0.795" classname="cases.CheckBoxCase">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at cases.CheckBoxCase.intentionalFailcheckBox(CheckBoxCase.java:62)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at GrandpaBless.main(GrandpaBless.java:81)
]]>
    </failure>
  </testcase> <!-- intentionalFailcheckBox -->
  <testcase name="checkBoxTwoThree" time="0.708" classname="cases.CheckBoxCase"/>
  <testcase name="checkBoxAll" time="1.244" classname="cases.CheckBoxCase"/>
  <testcase name="checkBoxOneThree" time="0.364" classname="cases.CheckBoxCase"/>
  <testcase name="checkBoxTwoThree" time="0.828" classname="cases.CheckBoxCase"/>
  <testcase name="checkBoxNone" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- checkBoxNone -->
  <testcase name="checkBoxOneTwo" time="0.830" classname="cases.CheckBoxCase"/>
</testsuite> <!-- cases.CheckBoxCase -->
