<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="18" hostname="linux-ThinkPad-E460" name="cases.CheckBoxCase" tests="51" failures="5" timestamp="28 Jul 2018 23:48:03 GMT" time="17.088" errors="3">
  <testcase name="beforeMethod" time="0.000" classname="cases.CheckBoxCase">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at cases.PapaBless.beforeMethod(PapaBless.java:341)
at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:520)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at GrandpaBless.main(GrandpaBless.java:82)
]]>
    </error>
  </testcase> <!-- beforeMethod -->
  <testcase name="beforeMethod" time="0.000" classname="cases.CheckBoxCase">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at cases.PapaBless.beforeMethod(PapaBless.java:341)
at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:520)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at GrandpaBless.main(GrandpaBless.java:82)
]]>
    </error>
  </testcase> <!-- beforeMethod -->
  <testcase name="beforeClass" time="0.013" classname="cases.CheckBoxCase">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at cases.PapaBless.beforeClass(PapaBless.java:333)
at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:168)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at GrandpaBless.main(GrandpaBless.java:82)
]]>
    </error>
  </testcase> <!-- beforeClass -->
  <testcase name="checkBoxAll" time="1.019" classname="cases.CheckBoxCase"/>
  <testcase name="intentionalFailcheckBox" time="0.723" classname="cases.CheckBoxCase">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at cases.CheckBoxCase.intentionalFailcheckBox(CheckBoxCase.java:60)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at GrandpaBless.main(GrandpaBless.java:82)
]]>
    </failure>
  </testcase> <!-- intentionalFailcheckBox -->
  <testcase name="checkBoxAll" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- checkBoxAll -->
  <testcase name="checkBoxOneThree" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- checkBoxOneThree -->
  <testcase name="checkBoxNone" time="0.201" classname="cases.CheckBoxCase"/>
  <testcase name="intentionalFailcheckBox" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- intentionalFailcheckBox -->
  <testcase name="checkBoxAll" time="0.437" classname="cases.CheckBoxCase"/>
  <testcase name="checkBoxNone" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- checkBoxNone -->
  <testcase name="checkBoxOneThree" time="0.338" classname="cases.CheckBoxCase"/>
  <testcase name="checkBoxOneTwo" time="0.730" classname="cases.CheckBoxCase"/>
  <testcase name="checkBoxNone" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- checkBoxNone -->
  <testcase name="intentionalFailcheckBox" time="0.735" classname="cases.CheckBoxCase">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at cases.CheckBoxCase.intentionalFailcheckBox(CheckBoxCase.java:60)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at GrandpaBless.main(GrandpaBless.java:82)
]]>
    </failure>
  </testcase> <!-- intentionalFailcheckBox -->
  <testcase name="checkBoxTwoThree" time="0.772" classname="cases.CheckBoxCase"/>
  <testcase name="intentionalFailcheckBox" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- intentionalFailcheckBox -->
  <testcase name="checkBoxAll" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- checkBoxAll -->
  <testcase name="checkBoxOneTwo" time="0.743" classname="cases.CheckBoxCase"/>
  <testcase name="intentionalFailcheckBox" time="0.309" classname="cases.CheckBoxCase">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at cases.CheckBoxCase.intentionalFailcheckBox(CheckBoxCase.java:60)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at GrandpaBless.main(GrandpaBless.java:82)
]]>
    </failure>
  </testcase> <!-- intentionalFailcheckBox -->
  <testcase name="checkBoxTwoThree" time="0.323" classname="cases.CheckBoxCase"/>
  <testcase name="checkBoxOneTwo" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- checkBoxOneTwo -->
  <testcase name="checkBoxNone" time="0.179" classname="cases.CheckBoxCase"/>
  <testcase name="checkBoxOneTwo" time="0.322" classname="cases.CheckBoxCase"/>
  <testcase name="checkBoxOneThree" time="0.386" classname="cases.CheckBoxCase"/>
  <testcase name="checkBoxTwoThree" time="0.776" classname="cases.CheckBoxCase"/>
  <testcase name="checkBoxOneThree" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- checkBoxOneThree -->
  <testcase name="checkBoxNone" time="0.210" classname="cases.CheckBoxCase"/>
  <testcase name="checkBoxNone" time="0.299" classname="cases.CheckBoxCase"/>
  <testcase name="checkBoxTwoThree" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- checkBoxTwoThree -->
  <testcase name="checkBoxOneTwo" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- checkBoxOneTwo -->
  <testcase name="intentionalFailcheckBox" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- intentionalFailcheckBox -->
  <testcase name="intentionalFailcheckBox" time="0.770" classname="cases.CheckBoxCase">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at cases.CheckBoxCase.intentionalFailcheckBox(CheckBoxCase.java:60)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at GrandpaBless.main(GrandpaBless.java:82)
]]>
    </failure>
  </testcase> <!-- intentionalFailcheckBox -->
  <testcase name="checkBoxAll" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- checkBoxAll -->
  <testcase name="checkBoxTwoThree" time="0.328" classname="cases.CheckBoxCase"/>
  <testcase name="checkBoxTwoThree" time="0.800" classname="cases.CheckBoxCase"/>
  <testcase name="checkBoxOneTwo" time="0.795" classname="cases.CheckBoxCase"/>
  <testcase name="checkBoxNone" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- checkBoxNone -->
  <testcase name="checkBoxAll" time="1.118" classname="cases.CheckBoxCase"/>
  <testcase name="checkBoxAll" time="0.447" classname="cases.CheckBoxCase"/>
  <testcase name="checkBoxAll" time="1.109" classname="cases.CheckBoxCase"/>
  <testcase name="checkBoxOneThree" time="0.793" classname="cases.CheckBoxCase"/>
  <testcase name="checkBoxTwoThree" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- checkBoxTwoThree -->
  <testcase name="intentionalFailcheckBox" time="0.323" classname="cases.CheckBoxCase">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at cases.CheckBoxCase.intentionalFailcheckBox(CheckBoxCase.java:60)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at GrandpaBless.main(GrandpaBless.java:82)
]]>
    </failure>
  </testcase> <!-- intentionalFailcheckBox -->
  <testcase name="checkBoxOneThree" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- checkBoxOneThree -->
  <testcase name="checkBoxOneTwo" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- checkBoxOneTwo -->
  <testcase name="checkBoxNone" time="0.218" classname="cases.CheckBoxCase"/>
  <testcase name="checkBoxTwoThree" time="0.000" classname="cases.CheckBoxCase">
    <skipped/>
  </testcase> <!-- checkBoxTwoThree -->
  <testcase name="checkBoxOneTwo" time="0.322" classname="cases.CheckBoxCase"/>
  <testcase name="checkBoxOneThree" time="0.781" classname="cases.CheckBoxCase"/>
  <testcase name="checkBoxOneThree" time="0.769" classname="cases.CheckBoxCase"/>
</testsuite> <!-- cases.CheckBoxCase -->
